name: Run Gradle on PRs
on: [push]
jobs:
  gradle:
    runs-on: ubuntu-20.04
    name: Run build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        name: build
        with:
          arguments: build