name: Build

on: [push]

jobs:
  python:
    strategy:
      matrix:
        python-version: [ '2.7', '3.6', '3.7', '3.8', '3.9' ]
    name: Run demistomock on python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python src/main/resources/META-INF/demistomock.py